name: release sqlite3
on:
  push:
    branches:
      - main
    paths:
      - 'sqlite3/**'
      - '.github/workflows/release-sqlite3.yaml'

jobs:
  release:
    name: Build and Release
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release Version
        id: version
        run: |
          export RELEASE_VERSION=v0.0.${{ github.run_number }}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: create tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a sqlite3/$RELEASE_VERSION -m sqlite3/$RELEASE_VERSION
          git push origin sqlite3/$RELEASE_VERSION

